import { ObjectId } from 'mongodb';

import {
  Gender,
  OrderStatus,
  PetCharacter,
  PetSize,
  ServiceType,
  SitterStatus,
  TaskPublic,
  TaskStatus,
} from '@prisma/client';

export const users = [
  {
    id: new ObjectId().toString(),
    email: 'user1@example.com',
    real_name: 'User One',
    phone: '123456789',
    password: 'hashed_password1',
    lastPasswordChange: new Date(),
    nickname: 'User1',
    birthdate: new Date('1990-01-01'),
    gender: Gender.MALE,
    self_introduction: 'Hello, I am User One',
    avatar: 'https://example.com/avatar1.jpg',
    is_sitter: false,
    is_deleted: false,
    average_rating: 4.5,
    total_reviews: 10,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: new ObjectId().toString(),
    email: 'user2@example.com',
    real_name: 'User Two',
    phone: '987654321',
    password: 'hashed_password2',
    lastPasswordChange: new Date(),
    nickname: 'User2',
    birthdate: new Date('1991-01-01'),
    gender: Gender.FEMALE,
    self_introduction: 'Hello, I am User Two',
    avatar: 'https://example.com/avatar2.jpg',
    is_sitter: true,
    is_deleted: false,
    average_rating: 4.7,
    total_reviews: 20,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: new ObjectId().toString(),
    email: 'user3@example.com',
    real_name: 'User Three',
    phone: '555555555',
    password: 'hashed_password3',
    lastPasswordChange: new Date(),
    nickname: 'User3',
    birthdate: new Date('1992-01-01'),
    gender: Gender.OTHER,
    self_introduction: 'Hello, I am User Three',
    avatar: 'https://example.com/avatar3.jpg',
    is_sitter: false,
    is_deleted: false,
    average_rating: 4.0,
    total_reviews: 5,
    created_at: new Date(),
    updated_at: new Date(),
  },
];

export const pets = [
  {
    id: new ObjectId().toString(),
    name: 'Pet One',
    breed: 'Breed One',
    size: PetSize.S,
    character_list: [PetCharacter.CUTE, PetCharacter.FRIENDLY],
    has_microchipped: true,
    is_neutered: true,
    health_description: 'Healthy pet',
    avatar_list: ['https://example.com/pet1.jpg'],
    created_at: new Date(),
    updated_at: new Date(),
    owner_user_id: users[0].id,
  },
  {
    id: new ObjectId().toString(),
    name: 'Pet Two',
    breed: 'Breed Two',
    size: PetSize.M,
    character_list: [PetCharacter.ENERGETIC, PetCharacter.SMART],
    has_microchipped: false,
    is_neutered: false,
    health_description: 'Very active',
    avatar_list: ['https://example.com/pet2.jpg'],
    created_at: new Date(),
    updated_at: new Date(),
    owner_user_id: users[1].id,
  },
  {
    id: new ObjectId().toString(),
    name: 'Pet Three',
    breed: 'Breed Three',
    size: PetSize.L,
    character_list: [PetCharacter.NAUGHTY, PetCharacter.GREEDY],
    has_microchipped: true,
    is_neutered: true,
    health_description: 'Loves to eat',
    avatar_list: ['https://example.com/pet3.jpg'],
    created_at: new Date(),
    updated_at: new Date(),
    owner_user_id: users[2].id,
  },
];

export const tasks = [
  {
    id: new ObjectId().toString(),
    title: 'Task One',
    public: TaskPublic.OPEN,
    status: TaskStatus.NULL,
    cover: 'https://example.com/cover1.jpg',
    service_type: ServiceType.PHOTOGRAPHY,
    city: 'City One',
    district: 'District One',
    unit_price: 100,
    total: 1,
    description: 'Task One Description',
    accept_sitter_contact: true,
    start_at: new Date(),
    end_at: new Date(new Date().getTime() + 60 * 60 * 1000),
    created_at: new Date(),
    updated_at: new Date(),
    user_id: users[0].id,
    pet_id: pets[0].id,
  },
  {
    id: new ObjectId().toString(),
    title: 'Task Two',
    public: TaskPublic.CLOSED,
    status: TaskStatus.PENDING,
    cover: 'https://example.com/cover2.jpg',
    service_type: ServiceType.HEALTH_CARE,
    city: 'City Two',
    district: 'District Two',
    unit_price: 200,
    total: 1,
    description: 'Task Two Description',
    accept_sitter_contact: true,
    start_at: new Date(),
    end_at: new Date(new Date().getTime() + 2 * 60 * 60 * 1000),
    created_at: new Date(),
    updated_at: new Date(),
    user_id: users[1].id,
    pet_id: pets[1].id,
  },
  {
    id: new ObjectId().toString(),
    title: 'Task Three',
    public: TaskPublic.IN_TRANSACTION,
    status: TaskStatus.TRACKING,
    cover: 'https://example.com/cover3.jpg',
    service_type: ServiceType.BATH,
    city: 'City Three',
    district: 'District Three',
    unit_price: 300,
    total: 1,
    description: 'Task Three Description',
    accept_sitter_contact: true,
    start_at: new Date(),
    end_at: new Date(new Date().getTime() + 3 * 60 * 60 * 1000),
    created_at: new Date(),
    updated_at: new Date(),
    user_id: users[2].id,
    pet_id: pets[2].id,
  },
];

export const comments = [
  {
    id: new ObjectId().toString(),
    parent_comment_id: null,
    author_id: users[0].id,
    text: 'Comment One',
    task_id: tasks[0].id,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: new ObjectId().toString(),
    parent_comment_id: null,
    author_id: users[1].id,
    text: 'Comment Two',
    task_id: tasks[1].id,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: new ObjectId().toString(),
    parent_comment_id: null,
    author_id: users[2].id,
    text: 'Comment Three',
    task_id: tasks[2].id,
    created_at: new Date(),
    updated_at: new Date(),
  },
];

export const sitters = [
  {
    id: new ObjectId().toString(),
    certificate_number: '123456',
    certificate_image: 'https://example.com/cert1.jpg',
    has_certificate: true,
    police_check_image: 'https://example.com/police1.jpg',
    has_police_check: true,
    service_city: 'City One',
    service_district_list: ['District One', 'District Two'],
    photography_price: 100,
    health_care_price: 200,
    bath_price: 300,
    walking_price: 400,
    service_size_list: [PetSize.S, PetSize.M],
    is_door_to_door: true,
    image_list: ['https://example.com/service1.jpg'],
    service_description: 'Sitter One Description',
    average_rating: 4.5,
    total_reviews: 10,
    status: SitterStatus.ON_BOARD,
    created_at: new Date(),
    updated_at: new Date(),
    user_id: users[0].id,
  },
  {
    id: new ObjectId().toString(),
    certificate_number: '654321',
    certificate_image: 'https://example.com/cert2.jpg',
    has_certificate: true,
    police_check_image: 'https://example.com/police2.jpg',
    has_police_check: false,
    service_city: 'City Two',
    service_district_list: ['District Three', 'District Four'],
    photography_price: 200,
    health_care_price: 300,
    bath_price: 400,
    walking_price: 500,
    service_size_list: [PetSize.M, PetSize.L],
    is_door_to_door: false,
    image_list: ['https://example.com/service2.jpg'],
    service_description: 'Sitter Two Description',
    average_rating: 4.7,
    total_reviews: 20,
    status: SitterStatus.APPROVING,
    created_at: new Date(),
    updated_at: new Date(),
    user_id: users[1].id,
  },
  {
    id: new ObjectId().toString(),
    certificate_number: '789012',
    certificate_image: 'https://example.com/cert3.jpg',
    has_certificate: false,
    police_check_image: 'https://example.com/police3.jpg',
    has_police_check: true,
    service_city: 'City Three',
    service_district_list: ['District Five', 'District Six'],
    photography_price: 300,
    health_care_price: 400,
    bath_price: 500,
    walking_price: 600,
    service_size_list: [PetSize.L],
    is_door_to_door: true,
    image_list: ['https://example.com/service3.jpg'],
    service_description: 'Sitter Three Description',
    average_rating: 4.0,
    total_reviews: 5,
    status: SitterStatus.REJECTED,
    created_at: new Date(),
    updated_at: new Date(),
    user_id: users[2].id,
  },
];

export const reviews = [
  {
    id: new ObjectId().toString(),
    pet_owner_user_id: users[0].id,
    pet_owner_rating: 5,
    pet_owner_content: 'Excellent service!',
    pet_owner_created_at: new Date(),
    pet_owner_updated_at: new Date(),
    sitter_user_id: users[1].id,
    sitter_rating: 4,
    sitter_content: 'Good experience',
    sitter_user_created_at: new Date(),
    sitter_user_updated_at: new Date(),
    task_id: tasks[0].id,
  },
  {
    id: new ObjectId().toString(),
    pet_owner_user_id: users[1].id,
    pet_owner_rating: 4,
    pet_owner_content: 'Very good service!',
    pet_owner_created_at: new Date(),
    pet_owner_updated_at: new Date(),
    sitter_user_id: users[2].id,
    sitter_rating: 5,
    sitter_content: 'Amazing experience',
    sitter_user_created_at: new Date(),
    sitter_user_updated_at: new Date(),
    task_id: tasks[1].id,
  },
  {
    id: new ObjectId().toString(),
    pet_owner_user_id: users[2].id,
    pet_owner_rating: 3,
    pet_owner_content: 'Good service!',
    pet_owner_created_at: new Date(),
    pet_owner_updated_at: new Date(),
    sitter_user_id: users[0].id,
    sitter_rating: 4,
    sitter_content: 'Nice experience',
    sitter_user_created_at: new Date(),
    sitter_user_updated_at: new Date(),
    task_id: tasks[2].id,
  },
];

export const orders = [
  {
    id: new ObjectId().toString(),
    sitter_user_id: users[1].id,
    pet_owner_user_id: users[0].id,
    status: OrderStatus.PENDING,
    note: 'Order One Note',
    payment_at: new Date(),
    report_content: 'Order One Report Content',
    report_image_list: ['https://example.com/report1.jpg'],
    report_created_at: new Date(),
    report_updated_at: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
    task_id: tasks[0].id,
  },
  {
    id: new ObjectId().toString(),
    sitter_user_id: users[2].id,
    pet_owner_user_id: users[1].id,
    status: OrderStatus.VALID,
    note: 'Order Two Note',
    payment_at: new Date(),
    report_content: 'Order Two Report Content',
    report_image_list: ['https://example.com/report2.jpg'],
    report_created_at: new Date(),
    report_updated_at: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
    task_id: tasks[1].id,
  },
  {
    id: new ObjectId().toString(),
    sitter_user_id: users[0].id,
    pet_owner_user_id: users[2].id,
    status: OrderStatus.COMPLETED,
    note: 'Order Three Note',
    payment_at: new Date(),
    report_content: 'Order Three Report Content',
    report_image_list: ['https://example.com/report3.jpg'],
    report_created_at: new Date(),
    report_updated_at: new Date(),
    created_at: new Date(),
    updated_at: new Date(),
    task_id: tasks[2].id,
  },
];
